<?php

header('Content-type: text/html; charset=utf-8');
error_reporting(E_ALL | E_STRICT);

$smiles = array(
    array(
        'id'       => 1,
        'name'     => 'AF',
        'title'    => 'Afghanistan',
        'replaces' => array('(flag:AF)'),
    ),
    array(
        'id'       => 2,
        'name'     => 'AL',
        'title'    => 'Albania',
        'replaces' => array('(flag:AL)'),
    ),
    array(
        'id'       => 3,
        'name'     => 'DZ',
        'title'    => 'Algeria',
        'replaces' => array('(flag:DZ)'),
    ),
    array(
        'id'       => 4,
        'name'     => 'AS',
        'title'    => 'American Samoa',
        'replaces' => array('(flag:AS)'),
    ),
    array(
        'id'       => 5,
        'name'     => 'AD',
        'title'    => 'Andorra',
        'replaces' => array('(flag:AD)'),
    ),
    array(
        'id'       => 6,
        'name'     => 'AO',
        'title'    => 'Angola',
        'replaces' => array('(flag:AO)'),
    ),
    array(
        'id'       => 7,
        'name'     => 'AI',
        'title'    => 'Anguilla',
        'replaces' => array('(flag:AI)'),
    ),
    array(
        'id'       => 8,
        'name'     => 'AQ',
        'title'    => 'Antarctica',
        'replaces' => array('(flag:AQ)'),
    ),
    array(
        'id'       => 9,
        'name'     => 'AG',
        'title'    => 'Antigua and Barbuda',
        'replaces' => array('(flag:AG)'),
    ),
    array(
        'id'       => 10,
        'name'     => 'AR',
        'title'    => 'Argentina',
        'replaces' => array('(flag:AR)'),
    ),
    array(
        'id'       => 11,
        'name'     => 'AM',
        'title'    => 'Armenia',
        'replaces' => array('(flag:AM)'),
    ),
    array(
        'id'       => 12,
        'name'     => 'AW',
        'title'    => 'Aruba',
        'replaces' => array('(flag:AW)'),
    ),
    array(
        'id'       => 13,
        'name'     => 'AU',
        'title'    => 'Australia',
        'replaces' => array('(flag:AU)'),
    ),
    array(
        'id'       => 14,
        'name'     => 'AT',
        'title'    => 'Austria',
        'replaces' => array('(flag:AT)'),
    ),
    array(
        'id'       => 15,
        'name'     => 'AZ',
        'title'    => 'Azerbaijan',
        'replaces' => array('(flag:AZ)'),
    ),
    array(
        'id'       => 16,
        'name'     => 'BS',
        'title'    => 'Bahamas',
        'replaces' => array('(flag:BS)'),
    ),
    array(
        'id'       => 17,
        'name'     => 'BH',
        'title'    => 'Bahrain',
        'replaces' => array('(flag:BH)'),
    ),
    array(
        'id'       => 18,
        'name'     => 'BD',
        'title'    => 'Bangladesh',
        'replaces' => array('(flag:BD)'),
    ),
    array(
        'id'       => 19,
        'name'     => 'BB',
        'title'    => 'Barbados',
        'replaces' => array('(flag:BB)'),
    ),
    array(
        'id'       => 20,
        'name'     => 'BY',
        'title'    => 'Belarus',
        'replaces' => array('(flag:BY)'),
    ),
    array(
        'id'       => 21,
        'name'     => 'BE',
        'title'    => 'Belgium',
        'replaces' => array('(flag:BE)'),
    ),
    array(
        'id'       => 22,
        'name'     => 'BZ',
        'title'    => 'Belize',
        'replaces' => array('(flag:BZ)'),
    ),
    array(
        'id'       => 23,
        'name'     => 'BJ',
        'title'    => 'Benin',
        'replaces' => array('(flag:BJ)'),
    ),
    array(
        'id'       => 24,
        'name'     => 'BM',
        'title'    => 'Bermuda',
        'replaces' => array('(flag:BM)'),
    ),
    array(
        'id'       => 25,
        'name'     => 'BT',
        'title'    => 'Bhutan',
        'replaces' => array('(flag:BT)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'BO',
        'title'    => 'Bolivia',
        'replaces' => array('(flag:BO)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'BA',
        'title'    => 'Bosnia and Herzegovina',
        'replaces' => array('(flag:BA)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'BW',
        'title'    => 'Botswana',
        'replaces' => array('(flag:BW)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'BR',
        'title'    => 'Brazil',
        'replaces' => array('(flag:BR)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'IO',
        'title'    => 'British Indian Ocean Territory',
        'replaces' => array('(flag:IO)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'VG',
        'title'    => 'British Virgin Islands',
        'replaces' => array('(flag:VG)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'BN',
        'title'    => 'Brunei Darussalam',
        'replaces' => array('(flag:BN)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'BG',
        'title'    => 'Bulgaria',
        'replaces' => array('(flag:BG)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'BF',
        'title'    => 'Burkina Faso',
        'replaces' => array('(flag:BF)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'BI',
        'title'    => 'Burundi',
        'replaces' => array('(flag:BI)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'KH',
        'title'    => 'Cambodia',
        'replaces' => array('(flag:KH)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'CM',
        'title'    => 'Cameroon',
        'replaces' => array('(flag:CM)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'CA',
        'title'    => 'Canada',
        'replaces' => array('(flag:CA)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'CV',
        'title'    => 'Cape Verde',
        'replaces' => array('(flag:CV)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'KY',
        'title'    => 'Cayman Islands',
        'replaces' => array('(flag:KY)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'CF',
        'title'    => 'Central African Republic',
        'replaces' => array('(flag:CF)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'TD',
        'title'    => 'Chad',
        'replaces' => array('(flag:TD)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'CL',
        'title'    => 'Chile',
        'replaces' => array('(flag:CL)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'CN',
        'title'    => 'China',
        'replaces' => array('(flag:CN)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'CX',
        'title'    => 'Christmas Island',
        'replaces' => array('(flag:CX)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'CC',
        'title'    => 'Cocos Islands',
        'replaces' => array('(flag:CC)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'CO',
        'title'    => 'Colombia',
        'replaces' => array('(flag:CO)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'KM',
        'title'    => 'Comoros',
        'replaces' => array('(flag:KM)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'CD',
        'title'    => 'Congo (DRC)',
        'replaces' => array('(flag:CD)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'CG',
        'title'    => 'Congo',
        'replaces' => array('(flag:CG)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'CK',
        'title'    => 'Cook Islands',
        'replaces' => array('(flag:CK)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'CR',
        'title'    => 'Costa Rica',
        'replaces' => array('(flag:CR)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'CI',
        'title'    => 'Cote D&rsquo;Ivoire',
        'replaces' => array('(flag:CI)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'CU',
        'title'    => 'Cuba',
        'replaces' => array('(flag:CU)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'CY',
        'title'    => 'Cyprus',
        'replaces' => array('(flag:CY)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'CZ',
        'title'    => 'Czech Republic',
        'replaces' => array('(flag:CZ)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'DK',
        'title'    => 'Denmark',
        'replaces' => array('(flag:DK)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'DJ',
        'title'    => 'Djibouti',
        'replaces' => array('(flag:DJ)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'DM',
        'title'    => 'Dominica',
        'replaces' => array('(flag:DM)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'DO',
        'title'    => 'Dominican Republic',
        'replaces' => array('(flag:DO)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'EC',
        'title'    => 'Ecuador',
        'replaces' => array('(flag:EC)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'EG',
        'title'    => 'Egypt',
        'replaces' => array('(flag:EG)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'EU',
        'title'    => 'European Union',
        'replaces' => array('(flag:EU)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'SV',
        'title'    => 'El Salvador',
        'replaces' => array('(flag:SV)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'GQ',
        'title'    => 'Equatorial Guinea',
        'replaces' => array('(flag:GQ)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'ER',
        'title'    => 'Eritrea',
        'replaces' => array('(flag:ER)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'EE',
        'title'    => 'Estonia',
        'replaces' => array('(flag:EE)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'ET',
        'title'    => 'Ethiopia',
        'replaces' => array('(flag:ET)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'FO',
        'title'    => 'Faroe Islands',
        'replaces' => array('(flag:FO)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'FK',
        'title'    => 'Falkland Islands',
        'replaces' => array('(flag:FK)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'FJ',
        'title'    => 'Fiji',
        'replaces' => array('(flag:FJ)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'FI',
        'title'    => 'Finland',
        'replaces' => array('(flag:FI)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'FR',
        'title'    => 'France',
        'replaces' => array('(flag:FR)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'GF',
        'title'    => 'French Guiana',
        'replaces' => array('(flag:GF)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'PF',
        'title'    => 'French Polynesia',
        'replaces' => array('(flag:PF)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'TF',
        'title'    => 'French Southern Territories',
        'replaces' => array('(flag:TF)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'GA',
        'title'    => 'Gabon',
        'replaces' => array('(flag:GA)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'GM',
        'title'    => 'Gambia',
        'replaces' => array('(flag:GM)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'GE',
        'title'    => 'Georgia',
        'replaces' => array('(flag:GE)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'DE',
        'title'    => 'Germany',
        'replaces' => array('(flag:DE)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'GH',
        'title'    => 'Ghana',
        'replaces' => array('(flag:GH)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'GI',
        'title'    => 'Gibraltar',
        'replaces' => array('(flag:GI)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'GR',
        'title'    => 'Greece',
        'replaces' => array('(flag:GR)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'GL',
        'title'    => 'Greenland',
        'replaces' => array('(flag:GL)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'GD',
        'title'    => 'Grenada',
        'replaces' => array('(flag:GD)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'GP',
        'title'    => 'Guadeloupe',
        'replaces' => array('(flag:GP)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'GU',
        'title'    => 'Guam',
        'replaces' => array('(flag:GU)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'GT',
        'title'    => 'Guatemala',
        'replaces' => array('(flag:GT)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'GN',
        'title'    => 'Guinea',
        'replaces' => array('(flag:GN)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'GW',
        'title'    => 'Guinea-Bissau',
        'replaces' => array('(flag:GW)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'GY',
        'title'    => 'Guyana',
        'replaces' => array('(flag:GY)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'HT',
        'title'    => 'Haiti',
        'replaces' => array('(flag:HT)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'HM',
        'title'    => 'Heard and McDonald Islands',
        'replaces' => array('(flag:HM)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'VA',
        'title'    => 'Holy See (Vatican City State)',
        'replaces' => array('(flag:VA)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'HN',
        'title'    => 'Honduras',
        'replaces' => array('(flag:HN)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'HK',
        'title'    => 'Hong Kong',
        'replaces' => array('(flag:HK)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'HR',
        'title'    => 'Croatia',
        'replaces' => array('(flag:HR)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'HU',
        'title'    => 'Hungary',
        'replaces' => array('(flag:HU)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'IS',
        'title'    => 'Iceland',
        'replaces' => array('(flag:IS)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'IN',
        'title'    => 'India',
        'replaces' => array('(flag:IN)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'ID',
        'title'    => 'Indonesia',
        'replaces' => array('(flag:ID)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'IR',
        'title'    => 'Iran',
        'replaces' => array('(flag:IR)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'IQ',
        'title'    => 'Iraq',
        'replaces' => array('(flag:IQ)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'IE',
        'title'    => 'Ireland',
        'replaces' => array('(flag:IE)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'IL',
        'title'    => 'Israel',
        'replaces' => array('(flag:IL)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'IT',
        'title'    => 'Italy',
        'replaces' => array('(flag:IT)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'JM',
        'title'    => 'Jamaica',
        'replaces' => array('(flag:JM)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'JP',
        'title'    => 'Japan',
        'replaces' => array('(flag:JP)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'JO',
        'title'    => 'Jordan',
        'replaces' => array('(flag:JO)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'KZ',
        'title'    => 'Kazakhstan',
        'replaces' => array('(flag:KZ)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'KE',
        'title'    => 'Kenya',
        'replaces' => array('(flag:KE)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'KI',
        'title'    => 'Kiribati',
        'replaces' => array('(flag:KI)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'KP',
        'title'    => 'North Korea',
        'replaces' => array('(flag:KP)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'KR',
        'title'    => 'Korea',
        'replaces' => array('(flag:KR)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'KW',
        'title'    => 'Kuwait',
        'replaces' => array('(flag:KW)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'KG',
        'title'    => 'Kyrgyz Republic',
        'replaces' => array('(flag:KG)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'LA',
        'title'    => 'Laos',
        'replaces' => array('(flag:LA)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'LV',
        'title'    => 'Latvia',
        'replaces' => array('(flag:LV)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'LB',
        'title'    => 'Lebanon',
        'replaces' => array('(flag:LB)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'LS',
        'title'    => 'Lesotho',
        'replaces' => array('(flag:LS)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'LR',
        'title'    => 'Liberia',
        'replaces' => array('(flag:LR)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'LY',
        'title'    => 'Libyan Arab Jamahiriya',
        'replaces' => array('(flag:LY)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'LI',
        'title'    => 'Liechtenstein',
        'replaces' => array('(flag:LI)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'LT',
        'title'    => 'Lithuania',
        'replaces' => array('(flag:LT)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'LU',
        'title'    => 'Luxembourg',
        'replaces' => array('(flag:LU)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'MO',
        'title'    => 'Macao',
        'replaces' => array('(flag:MO)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'ME',
        'title'    => 'Montenegro',
        'replaces' => array('(flag:ME)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'MK',
        'title'    => 'Macedonia',
        'replaces' => array('(flag:MK)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'MG',
        'title'    => 'Madagascar',
        'replaces' => array('(flag:MG)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'MW',
        'title'    => 'Malawi',
        'replaces' => array('(flag:MW)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'MY',
        'title'    => 'Malaysia',
        'replaces' => array('(flag:MY)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'MV',
        'title'    => 'Maldives',
        'replaces' => array('(flag:MV)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'ML',
        'title'    => 'Mali',
        'replaces' => array('(flag:ML)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'MT',
        'title'    => 'Malta',
        'replaces' => array('(flag:MT)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'MH',
        'title'    => 'Marshall Islands',
        'replaces' => array('(flag:MH)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'MQ',
        'title'    => 'Martinique',
        'replaces' => array('(flag:MQ)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'MR',
        'title'    => 'Mauritania',
        'replaces' => array('(flag:MR)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'MU',
        'title'    => 'Mauritius',
        'replaces' => array('(flag:MU)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'YT',
        'title'    => 'Mayotte',
        'replaces' => array('(flag:YT)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'MX',
        'title'    => 'Mexico',
        'replaces' => array('(flag:MX)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'FM',
        'title'    => 'Micronesia',
        'replaces' => array('(flag:FM)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'MD',
        'title'    => 'Moldova',
        'replaces' => array('(flag:MD)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'MC',
        'title'    => 'Monaco',
        'replaces' => array('(flag:MC)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'MN',
        'title'    => 'Mongolia',
        'replaces' => array('(flag:MN)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'ME',
        'title'    => 'Montenegro',
        'replaces' => array('(flag:ME)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'MS',
        'title'    => 'Montserrat',
        'replaces' => array('(flag:MS)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'MA',
        'title'    => 'Morocco',
        'replaces' => array('(flag:MA)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'MZ',
        'title'    => 'Mozambique',
        'replaces' => array('(flag:MZ)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'MM',
        'title'    => 'Myanmar',
        'replaces' => array('(flag:MM)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'NA',
        'title'    => 'Namibia',
        'replaces' => array('(flag:NA)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'NR',
        'title'    => 'Nauru',
        'replaces' => array('(flag:NR)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'NP',
        'title'    => 'Nepal',
        'replaces' => array('(flag:NP)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'NL',
        'title'    => 'Netherlands',
        'replaces' => array('(flag:NL)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'NC',
        'title'    => 'New Caledonia',
        'replaces' => array('(flag:NC)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'NZ',
        'title'    => 'New Zealand',
        'replaces' => array('(flag:NZ)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'NI',
        'title'    => 'Nicaragua',
        'replaces' => array('(flag:NI)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'NE',
        'title'    => 'Niger',
        'replaces' => array('(flag:NE)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'NG',
        'title'    => 'Nigeria',
        'replaces' => array('(flag:NG)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'NU',
        'title'    => 'Niue',
        'replaces' => array('(flag:NU)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'NF',
        'title'    => 'Norfolk Island',
        'replaces' => array('(flag:NF)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'MP',
        'title'    => 'Northern Mariana Islands',
        'replaces' => array('(flag:MP)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'NO',
        'title'    => 'Norway',
        'replaces' => array('(flag:NO)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'OM',
        'title'    => 'Oman',
        'replaces' => array('(flag:OM)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'PK',
        'title'    => 'Pakistan',
        'replaces' => array('(flag:PK)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'PW',
        'title'    => 'Palau',
        'replaces' => array('(flag:PW)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'PS',
        'title'    => 'Palestine',
        'replaces' => array('(flag:PS)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'PA',
        'title'    => 'Panama',
        'replaces' => array('(flag:PA)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'PG',
        'title'    => 'Papua New Guinea',
        'replaces' => array('(flag:PG)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'PY',
        'title'    => 'Paraguay',
        'replaces' => array('(flag:PY)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'PE',
        'title'    => 'Peru',
        'replaces' => array('(flag:PE)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'PH',
        'title'    => 'Philippines',
        'replaces' => array('(flag:PH)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'PN',
        'title'    => 'Pitcairn Island',
        'replaces' => array('(flag:PN)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'PL',
        'title'    => 'Poland',
        'replaces' => array('(flag:PL)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'PT',
        'title'    => 'Portugal',
        'replaces' => array('(flag:PT)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'PR',
        'title'    => 'Puerto Rico',
        'replaces' => array('(flag:PR)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'QA',
        'title'    => 'Qatar',
        'replaces' => array('(flag:QA)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'RE',
        'title'    => 'Reunion',
        'replaces' => array('(flag:RE)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'RO',
        'title'    => 'Romania',
        'replaces' => array('(flag:RO)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'RU',
        'title'    => 'Russian Federation',
        'replaces' => array('(flag:RU)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'RW',
        'title'    => 'Rwanda',
        'replaces' => array('(flag:RW)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'RS',
        'title'    => 'Serbia',
        'replaces' => array('(flag:RS)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'SS',
        'title'    => 'South Sudan',
        'replaces' => array('(flag:SS)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'WS',
        'title'    => 'Samoa',
        'replaces' => array('(flag:WS)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'SM',
        'title'    => 'San Marino',
        'replaces' => array('(flag:SM)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'ST',
        'title'    => 'Sao Tome and Principe',
        'replaces' => array('(flag:ST)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'SA',
        'title'    => 'Saudi Arabia',
        'replaces' => array('(flag:SA)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'SN',
        'title'    => 'Senegal',
        'replaces' => array('(flag:SN)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'RS',
        'title'    => 'Serbia',
        'replaces' => array('(flag:RS)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'SC',
        'title'    => 'Seychelles',
        'replaces' => array('(flag:SC)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'SL',
        'title'    => 'Sierra Leone',
        'replaces' => array('(flag:SL)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'SG',
        'title'    => 'Singapore',
        'replaces' => array('(flag:SG)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'SK',
        'title'    => 'Slovakia',
        'replaces' => array('(flag:SK)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'SI',
        'title'    => 'Slovenia',
        'replaces' => array('(flag:SI)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'SB',
        'title'    => 'Solomon Islands',
        'replaces' => array('(flag:SB)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'SO',
        'title'    => 'Somalia',
        'replaces' => array('(flag:SO)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'ZA',
        'title'    => 'South Africa',
        'replaces' => array('(flag:ZA)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'ES',
        'title'    => 'Spain',
        'replaces' => array('(flag:ES)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'LK',
        'title'    => 'Sri Lanka',
        'replaces' => array('(flag:LK)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'SH',
        'title'    => 'St. Helena',
        'replaces' => array('(flag:SH)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'KN',
        'title'    => 'St. Kitts and Nevis',
        'replaces' => array('(flag:KN)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'LC',
        'title'    => 'St. Lucia',
        'replaces' => array('(flag:LC)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'PM',
        'title'    => 'St. Pierre and Miquelon',
        'replaces' => array('(flag:PM)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'VC',
        'title'    => 'St. Vincent and the Grenadines',
        'replaces' => array('(flag:VC)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'SD',
        'title'    => 'Sudan',
        'replaces' => array('(flag:SD)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'SR',
        'title'    => 'Suriname',
        'replaces' => array('(flag:SR)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'SZ',
        'title'    => 'Swaziland',
        'replaces' => array('(flag:SZ)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'SE',
        'title'    => 'Sweden',
        'replaces' => array('(flag:SE)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'CH',
        'title'    => 'Switzerland',
        'replaces' => array('(flag:CH)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'SY',
        'title'    => 'Syria',
        'replaces' => array('(flag:SY)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'TW',
        'title'    => 'Taiwan',
        'replaces' => array('(flag:TW)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'TJ',
        'title'    => 'Tajikistan',
        'replaces' => array('(flag:TJ)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'TZ',
        'title'    => 'Tanzania',
        'replaces' => array('(flag:TZ)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'TH',
        'title'    => 'Thailand',
        'replaces' => array('(flag:TH)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'TL',
        'title'    => 'Timor-Leste',
        'replaces' => array('(flag:TL)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'TG',
        'title'    => 'Togo',
        'replaces' => array('(flag:TG)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'TK',
        'title'    => 'Tokelau',
        'replaces' => array('(flag:TK)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'TO',
        'title'    => 'Tonga',
        'replaces' => array('(flag:TO)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'TT',
        'title'    => 'Trinidad and Tobago',
        'replaces' => array('(flag:TT)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'TN',
        'title'    => 'Tunisia',
        'replaces' => array('(flag:TN)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'TR',
        'title'    => 'Turkey',
        'replaces' => array('(flag:TR)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'TM',
        'title'    => 'Turkmenistan',
        'replaces' => array('(flag:TM)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'TC',
        'title'    => 'Turks and Caicos Islands',
        'replaces' => array('(flag:TC)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'TV',
        'title'    => 'Tuvalu',
        'replaces' => array('(flag:TV)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'VI',
        'title'    => 'US Virgin Islands',
        'replaces' => array('(flag:VI)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'UG',
        'title'    => 'Uganda',
        'replaces' => array('(flag:UG)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'UA',
        'title'    => 'Ukraine',
        'replaces' => array('(flag:UA)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'AE',
        'title'    => 'United Arab Emirates',
        'replaces' => array('(flag:AE)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'GB',
        'title'    => 'United Kingdom',
        'replaces' => array('(flag:GB)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'US',
        'title'    => 'United States of America',
        'replaces' => array('(flag:US)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'UY',
        'title'    => 'Uruguay',
        'replaces' => array('(flag:UY)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'UZ',
        'title'    => 'Uzbekistan',
        'replaces' => array('(flag:UZ)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'VU',
        'title'    => 'Vanuatu',
        'replaces' => array('(flag:VU)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'VE',
        'title'    => 'Venezuela',
        'replaces' => array('(flag:VE)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'VN',
        'title'    => 'Viet Nam',
        'replaces' => array('(flag:VN)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'WF',
        'title'    => 'Wallis and Futuna Islands',
        'replaces' => array('(flag:WF)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'YE',
        'title'    => 'Yemen',
        'replaces' => array('(flag:YE)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'ZM',
        'title'    => 'Zambia',
        'replaces' => array('(flag:ZM)'),
    ),
    array(
        'id'       => 1,
        'name'     => 'ZW',
        'title'    => 'Zimbabwe',
        'replaces' => array('(flag:ZW)'),
    ),
);

$id = 1;
echo '<pre>';
foreach ($smiles as $smile) {
    $title = htmlspecialchars($smile['replaces'][0]);
    echo <<<T
'$title',
T;
    $id++;
}
echo '</pre>';
